targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/**
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
        generate_for:
          - lib/**
      riverpod_generator:
        generate_for:
          - lib/**
      drift_dev:
        generate_for:
          - lib/**
